const words = [
    "cock",
    "dick",
    "weener",
    "shaft",
    "stick",
    "peepee",
    "peter",
    "shlong",
    "sausage",
    "cock",
    "girl stick",
    "gock",
    "weewee",
    "pudd",
    "meat",
    "boy meat",
    "girl meat",
    "weenor",
    "wiwi",
    "length",
    "member",
    "weenie doodle",
    "johnson",
    "knob",
    "pecker",
    "wang",
    "shlangy wangy",
    "queenis",
    "phallus",
    "erection",
    "pizzle",
    "tool",
    "rod",
    "ding-a-ling",
    "dong",
    "manhood",
    "womanhood",
    "thingtube",
    "willy",
    "whang",
    "prong",
    "plonker",
    "stiffy",
    "needle",
    "disco stick",
    "noodle",
    "dohickey",
    "contraption",
    "cream stick",
    "instrument",
    "magic wand",
    "sha boing boing",
    "wing ding doodle",
    "long dick style",
    "raquaza",
    "ancient beast",
    "hog",
    "dragon",
    "future beast",
    "french fry",
    "carrot",
    "egg plant",
    "mozzarella stick",
    "corn dog",
    "hot dog",
    "dog",
    "knife",
    "large meat stick",
    "https://pbs.twimg.com/media/FbXfyMrXgAMMSoN?format=png&name=smallyanky doodle",
    "shloing",
    "woowaa",
    "banana",
    "big girl",
    "dingaling",
    "ding dong",
    "firehose",
    "gold finger",
    "jack hammer",
    "JUNIOR",
    "junk",
    "knob",
    "rollercoaster",
    "Krull the Warrior King",
    "little guy",
    "lollipop",
    "donkey kong",
    "dirk",
    "dink",
    "maepole",
    "shmekl",
    "tallywacker",
    "shlangy wangy",
    "peener",
    "peenois",
    "inker",
    "splatsplat",
    "birdie",
    "dinosaurmutton chops",
    "pork",
    "cigar",
    "smoking stick",
    "pee-er",
    "sprinkler",
    "wood",
    "sapling",
    "tree",
    "sprout",
    "doing",
    "doingdoing",
    "agent cooper",
    "the big one",
    "my little guy",
    "my son",
    "peepaws piddle padder",
    "paddle",
    "sword",
    "shank",
    "spoon",
    "fork",
    "squid",
    "pingas",
    "pongo",
    "peeper",
    "weewort",
    "meat stick of the streets",
    "untamable animal",
    "wolf",
    "alien object",
    "insect squasher",
    "baby maker",
    "girl sexer",
    "boy sexer",
    "girl cock",
    "weenie",
    "weenier",
    "hot dog",
    "chili dog",
    "rewards member",
    "girl liker",
    "big daniel",
    "little danile",
    "prized possession",
    "object",
    "treasure",
    "gift",
    "gummy worm",
    "worm",
    "go-go-gadget meat shaft",
    "sneed",
    "whispy wood",
    "pee",
    "chubbendicken",
    "weeweeweapon",
    "rooster",
    "hooter",
    "penord",
    "meat candle",
    "cupman",
    "ancient Egyptian artifact",
    "fortnite axe",
    "my tilted tower",
    "shifty shaft",
    "she/her stick",
    "mechanical stick of truth",
    "nutmeg nard",
    "evil penis",
    "trophy",
    "fish stick",
    "risky reel",
    "THE ONE PIECE",
    "rook",
    "pawn",
    "solider",
    "little jimmy",
    "slippin jimmy",
    "uncle jimmy",
    "kanye south",
    "the dick from down unda",
    "are we petering,,, or are we just lois ?",
    "queen's scepter",
    "woman wand",
    "GIRL DICK",
    "doll dohickey",
    "estrogen elongated",
    "hero",
    "rob from smash bros",
    "garlic knot",
    "bread stick",
    "water balloon",
    "wild boar",
    "senior",
    "divine creation",
    "family jewel",
    "rock salt lamb",
    "peenius genius",
    "jk rowling",
    "cardboard",
    "excalibur",
    "fall guy",
    "picha",
    "pene",
    "pito",
    "panocho",
    "panocha",
    "verga",
    "Meat Scepter",
    "glizzy",
    "big tonka",
    "operator",
    "grammy",
    "vandal",
    "puzzle piece",
    "nail",
    "blue eye white dragon",
    "wanker",
    "hamburger",
    "nuclear bomb",
    "jolly rancher",
    "battle bus",
    "rick",
    "morty",
    "girth",
    "bowser",
    "little diddy",
    "dark vader",
    "ludwig",
    "death rod",
    "not what it used to be",
    "enchanted item",
    "mushroom",
    "sex pervert",
    "austin's power",
    "tomi's tomeat",
    "dark brandon",
    "gum-gum pistol",
    "shmekl",
    "King K. Rool",
    "Funky kong",
    "Dixie Kong",
    "Candy kong",
    "Cranky Kong",
    "doo-dad",
    "whiscash",
    "brisket",
    "crotch boob",
    "salamander",
    "team fort too too",
    "mae sword",
    "tgirl swag",
    "tgirl shaft",
    "baldi's basic",
    "the ink machine",
    "barbarian king",
    "mr gus",
    "penis steve",
    "https://pbs.twimg.com/media/FbYf6ayXEAAQl7q?format=png&name=360x360",
    "aunt grandma",
    "springlock",
    "tommys innit",
    "the griddy",
    "the goat",
    "gerret bobby furgeson",
    "mister chief",
    "lamb",
    "slaughter stick",
    "breakcore",
    "splatoon",
    "spaltoon 2",
    "spaltoon 3",
    "dunkey",
    "goku power",
    "the dragon stick",
    "baby yoda",
    "my adventure time",
    "bugsnack",
    "kamemamama",
    "lort",
    "lorax",
    "flomp",
    "sweet bread",
    "dragon balls and shaft",
    "princess stick",
    "princess bubble gum",
    "battle dick",
    "sauce master",
    "ultra david",
    "bus driver",
    "dance",
    "dance monkey",
    "third leg",
    "ai generated art",
    "two piece",
    "nuget",
    "cheese burger",
    "monke y d luffy",
    "markiplier",
    "wingstop",
    "softee",
    "BERUS",
    "skitty doohickey",
    "garchomp",
    "night time nasal",
    "toothpick",
    "baja blaster",
    "machine wiener",
    "remote pipebomb",
    "projectiles",
    "guardian",
    "THE MOON",
    "milky rock",
    "lebron games",
    "the bron bron hammer",
    "take it down tinkle town",
    "tinkle",
    "tonk",
    "tootoo",
    "yoinky",
    "yanker",
    "janker",
    "hanker",
    "poker",
    "coin grabber",
    "dick shift",
    "epic mickey",
    "sailors delight",
    "the anchor",
    "hammer",
    "mallet",
    "pipebomb",
    "crowbar",
    "rusty pipe",
    "pipe",
    "stump",
    "chode",
    "shlanky",
    "didi",
    "white knight",
    "unsheathed blade",
    "trubish",
    "gentlemans cane",
    "lady umbrella",
    "wombo comboer",
    "c-stick",
    "meat grinder",
    "hoe cakes",
    "corn nard",
    "nardward",
    "weird weewee",
    "human volcano",
    "underwater urchin",
    "evil creature",
    "queen of the unknown",
    "premarital sex haver",
    "involuntary penis",
    "irvin",
    "2% milk",
    "serve",
    "ding dong",
    "song bird",
    "stuffed crust",
    "domino's pizza effect",
    "strange spaghetti",
    "unusual long creature",
    "baby cakes",
    "freddy faz bear",
    "gold ingot",
    "brick",
    "clay maker",
    "mordicai",
    "rugby",
    "footlong",
    "scepter",
    "pen",
    "glue stick",
    "invention",
    "meat folder",
    "baby blower",
    "vegeta",
    "my little joker",
    "stewie griffin",
    "peeley (from fortnite)",
    "ghetsel thing",
    "lopunny lover",
    "ROUGH GAY SEX",
]

/** @typedef {string} publicKey */
addEventListener('fetch', event => {
    event.respondWith(handleRequest(event.request))
})

// https://github.com/discord/discord-interactions-js/blob/main/src/index.ts
// https://github.com/discord/discord-interactions-js/blob/main/src/index.ts
/**
 * Merge two arrays.
 *
 * @param {Uint8Array} arr1 - First array
 * @param {Uint8Array} arr2 - Second array
 * @returns {Uint8Array} Concatenated arrays
 */
function concatUint8Arrays(arr1, arr2) {
    const merged = new Uint8Array(arr1.length + arr2.length);
    merged.set(arr1);
    merged.set(arr2, arr1.length);
    return merged;
}

/**
 * Validates a payload from Discord against its signature and key.
 *
 * @param {string} body - The raw payload data
 * @param {string} signature - The signature from the `X-Signature-Ed25519` header
 * @param {string} timestamp - The timestamp from the `X-Signature-Timestamp` header
 * @param {string} clientPublicKey - The public key from the Discord developer dashboard
 * @returns {Promise<boolean>} Whether or not validation was successful
 */
async function verifyKey(
    body,
    signature,
    timestamp,
    clientPublicKey,
) {
    try {
        const timestampData = new TextEncoder().encode(timestamp);
        const bodyData = new TextEncoder().encode(body);
        const message = concatUint8Arrays(timestampData, bodyData);

        const signatureData = new Uint8Array(signature.match(/.{2}/g).map((byte) => parseInt(byte, 16)));
        const publicKeyData = new Uint8Array(clientPublicKey.match(/.{2}/g).map((byte) => parseInt(byte, 16)));
        const algorithm = {name: 'NODE-ED25519', namedCurve: 'NODE-ED25519'};
        const publicKey = await crypto.subtle.importKey("raw", publicKeyData, algorithm, true, ["verify"]);
        return await crypto.subtle.verify(algorithm, publicKey, signatureData, message);
        // return nacl.sign.detached.verify(message, signatureData, publicKeyData);
    } catch (ex) {
        return false;
    }
}

/**
 * Respond with hello worker text
 * @param {Request} request
 */
async function handleRequest(request) {
    const signature = request.headers.get("X-Signature-Ed25519") ?? "";
    const timestamp = request.headers.get("X-Signature-Timestamp") ?? "";

    const bodyText = await request.text()
    if(!await verifyKey(bodyText, signature, timestamp, publicKey)) {
        return new Response("", {
            status: 400
        });
    }
    const body = JSON.parse(bodyText)
    if(body.type === 1) {
        return new Response(JSON.stringify({
            "type": 1
        }), {
            headers: {
                "Content-Type": "application/json"
            }
        })
    }
    return new Response(JSON.stringify({
        "type": 4,
        "data": {
            "content": words[Math.floor(Math.random()*words.length)],
            "allowed_mentions": {"parse": []}
        }
    }), {
        headers: {
            "Content-Type": "application/json"
        }
    })
}